POS_MOD_CLASS_LABEL = "Represent the class label: "
POS_MOD_IMAGE_CAPTION = "Represent the image caption: "
POS_MOD_ANSWER = "Represent the answer: "
POS_MOD_DICT = {
    "ImageNet-1K": POS_MOD_CLASS_LABEL, "HatefulMemes":POS_MOD_CLASS_LABEL, "SUN397":POS_MOD_CLASS_LABEL, "N24News":POS_MOD_CLASS_LABEL, "VOC2007":POS_MOD_CLASS_LABEL, "Place365":POS_MOD_CLASS_LABEL,"ImageNet-A":POS_MOD_CLASS_LABEL, "ImageNet-R":POS_MOD_CLASS_LABEL, "ObjectNet":POS_MOD_CLASS_LABEL, "Country211":POS_MOD_CLASS_LABEL,
    "OK-VQA":POS_MOD_ANSWER, "A-OKVQA":POS_MOD_ANSWER, "DocVQA":POS_MOD_ANSWER, "InfographicsVQA":POS_MOD_ANSWER, "ChartQA":POS_MOD_ANSWER, "Visual7W":POS_MOD_ANSWER,"ScienceQA":POS_MOD_ANSWER, "GQA":POS_MOD_ANSWER, "TextVQA":POS_MOD_ANSWER, "VizWiz":POS_MOD_ANSWER,
    "MSCOCO_i2t":POS_MOD_IMAGE_CAPTION, "VisualNews_i2t":POS_MOD_IMAGE_CAPTION,
}